import React, { createContext, useContext, useState } from 'react';


const translations = {
  en: {
    // Navbar
    create: 'Create', orders: 'Orders', bilanc: 'Balance', materials: 'Materials', carInsurance: 'Car Insurance',
    // Create page
    createOrder: 'Create Order', createOrderSub: 'Fill in the details to create a new stone order',
    clientInfo: 'Client Information', fullName: 'Full Name', phoneNumber: 'Phone Number',
    location: 'Location', dueDate: 'Due Date', materialsLabel: 'Materials',
    addMaterial: 'Add Material', selectMaterial: 'Select a material', dimensions: 'Dimensions (meters)',
    quantity: 'Quantity', pricePerUnit: 'Price per unit', total: 'Total',
    additionalCosts: 'Additional Costs', addCost: 'Add Cost', noAdditionalCosts: 'No additional costs added.',
    amountEur: 'Amount (EUR)', reasonCost: 'Reason for this cost', comment: 'Comment',
    commentPlaceholder: 'Any special notes or instructions...', calculated: 'Calculated',
    cost: 'Cost', cancel: 'Cancel', createOrderBtn: 'Create Order',
    noMaterialsAvailable: 'No materials available. Please add in', first: 'first',
    item: 'Item',
    // Orders page
    ordersTitle: 'Orders', ordersSub: 'Manage and track all your stone orders',
    searchOrders: 'Search orders by name, material, location, phone...',
    pending: 'Pending', approved: 'Approved', declined: 'Declined',
    noOrders: 'No orders', noPendingOrders: 'No pending orders at the moment',
    noApprovedOrders: 'No approved orders yet', noDeclinedOrders: 'No declined orders',
    fullNameCol: 'Full Name', materialCol: 'Material(s)', priceCol: 'Price (EUR)', actionsCol: 'Actions',
    details: 'Details', orderDetails: 'Order Details', phone: 'Phone',
    close: 'Close', print: 'Print', saveChanges: 'Save Changes', editOrder: 'Edit Order',
    deleteOrderConfirm: 'Delete this order permanently?',
    // Bilanc page
    bilancTitle: 'Bilanc', bilancSub: 'Track debts and payments for approved orders',
    borxhe: 'Debts', tePaguara: 'Paid', totaliBorxheve: 'Total debts',
    pjeserishtTePaguara: 'Partially paid', totalRemainingUnpaid: 'Total remaining unpaid across all debts',
    totalPartialPayments: 'Total partial payments received so far', totalPaguara: 'Totali i Paguara',
    noOutstandingDebts: 'No outstanding debts', noPaidOrders: 'No paid orders',
    approvedOrdersAppear: 'Approved orders with outstanding balances will appear here',
    paidOrdersAppear: 'Fully paid orders will appear here',
    searchBilanc: 'Search by name, material, location, phone...',
    totalCol: 'Total (EUR)', paidCol: 'Paid (EUR)', remainingCol: 'Remaining (EUR)',
    ePaguar: 'E Paguar', kthejeNeBorxhe: 'Ktheje në Borxhe',
    paymentTitle: 'Payment', toBePaid: 'To Be Paid', addTransaction: 'Add Transaction',
    subtractPayment: 'Subtract a payment the client has made',
    addCorrection: 'Add a correction (undo an accidental payment)', apply: 'Apply',
    payment: 'Payment', correction: 'Correction', remaining: 'Remaining',
    paid: 'Paid',
    // Materials page
    materialsTitle: 'Materials', materialsSub: 'Manage your stone, granite, and hand craft inventory',
    searchMaterials: 'Search materials by name, code, or count...',
    standardMaterials: 'Materials', handcraftMaterials: 'Hand Craft Materials',
    noMaterialsYet: 'No materials yet', noHandcraftYet: 'No hand craft materials yet',
    addMaterialBtn: 'Add Material', editMaterial: 'Edit Material', addMaterialTitle: 'Add Material',
    materialType: 'Material Type', materialName: 'Material Name', materialCode: 'Material Code',
    pricePerM2: 'Price per m²', price: 'Price (EUR)', count: 'Count',
    deleteMaterial: 'Delete Material', deleteMaterialConfirm: 'Are you sure you want to delete this material? This action cannot be undone.',
    delete: 'Delete', code: 'Code',
    // Car Insurance page
    carInsuranceTitle: 'Car Insurance', carInsuranceSub: 'Track vehicle insurance policies and expiration dates',
    searchCars: 'Search by car name or plate number...',
    noCarsRegistered: 'No cars registered', noCarsFound: 'No cars found',
    addFirstVehicle: 'Add your first vehicle to track its insurance',
    tryDifferentSearch: 'Try a different search term',
    addCar: 'Add Car', editCarInsurance: 'Edit Car Insurance', addCarInsurance: 'Add Car Insurance',
    carName: 'Car Name (Make and Model)', plateNumber: 'Plate Number',
    startDate: 'Start Date', endDate: 'End Date',
    carCol: 'Car', plateCol: 'Plate Number', statusCol: 'Status',
    active: 'Active', expiringSoon: 'Expiring Soon', expired: 'Expired',
    deleteCar: 'Delete Car', deleteCarConfirm: 'Are you sure you want to delete this car insurance record? This action cannot be undone.',
  },

  mk: {
    create: 'Создади', orders: 'Нарачки', bilanc: 'Биланс', materials: 'Материјали', carInsurance: 'Авто Осигурување',
    createOrder: 'Создади Нарачка', createOrderSub: 'Пополнете ги деталите за создавање нова нарачка',
    clientInfo: 'Информации за клиент', fullName: 'Целосно Име', phoneNumber: 'Телефонски Број',
    location: 'Локација', dueDate: 'Краен Рок', materialsLabel: 'Материјали',
    addMaterial: 'Додади Материјал', selectMaterial: 'Изберете материјал', dimensions: 'Димензии (метри)',
    quantity: 'Количина', pricePerUnit: 'Цена по единица', total: 'Вкупно',
    additionalCosts: 'Дополнителни Трошоци', addCost: 'Додади Трошок', noAdditionalCosts: 'Нема додадено дополнителни трошоци.',
    amountEur: 'Износ (EUR)', reasonCost: 'Причина за трошокот', comment: 'Коментар',
    commentPlaceholder: 'Посебни белешки или инструкции...', calculated: 'Пресметано',
    cost: 'Цена', cancel: 'Откажи', createOrderBtn: 'Создади Нарачка',
    noMaterialsAvailable: 'Нема достапни материјали. Додадете во', first: 'прво',
    item: 'Ставка',
    ordersTitle: 'Нарачки', ordersSub: 'Управувајте и следете ги сите нарачки',
    searchOrders: 'Пребарај нарачки по ime, материјал, локација...',
    pending: 'На чекање', approved: 'Одобрени', declined: 'Одбиени',
    noOrders: 'Нема нарачки', noPendingOrders: 'Нема нарачки на чекање',
    noApprovedOrders: 'Нема одобрени нарачки', noDeclinedOrders: 'Нема одбиени нарачки',
    fullNameCol: 'Целосно Име', materialCol: 'Материјал(и)', priceCol: 'Цена (EUR)', actionsCol: 'Акции',
    details: 'Детали', orderDetails: 'Детали на нарачка', phone: 'Телефон',
    close: 'Затвори', print: 'Печати', saveChanges: 'Зачувај Промени', editOrder: 'Уреди Нарачка',
    deleteOrderConfirm: 'Трајно да се избрише нарачката?',
    bilancTitle: 'Биланс', bilancSub: 'Следете долгови и плаќања за одобрени нарачки',
    borxhe: 'Долгови', tePaguara: 'Платени', totaliBorxheve: 'Вкупно долгови',
    pjeserishtTePaguara: 'Делумно платени', totalRemainingUnpaid: 'Вкупно неплатено',
    totalPartialPayments: 'Вкупно делумни плаќања', totalPaguara: 'Вкупно платено',
    noOutstandingDebts: 'Нема неплатени долгови', noPaidOrders: 'Нема платени нарачки',
    approvedOrdersAppear: 'Одобрените нарачки со неплатени салда ќе се прикажат овде',
    paidOrdersAppear: 'Целосно платените нарачки ќе се прикажат овде',
    searchBilanc: 'Пребарај по ime, материјал, локација...',
    totalCol: 'Вкупно (EUR)', paidCol: 'Платено (EUR)', remainingCol: 'Остаток (EUR)',
    ePaguar: 'Платено', kthejeNeBorxhe: 'Врати во Долгови',
    paymentTitle: 'Плаќање', toBePaid: 'За Плаќање', addTransaction: 'Додади Трансакција',
    subtractPayment: 'Одземи плаќање на клиентот', addCorrection: 'Додади корекција', apply: 'Примени',
    payment: 'Плаќање', correction: 'Корекција', remaining: 'Остаток', paid: 'Платено',
    materialsTitle: 'Материјали', materialsSub: 'Управувајте со залихите на камен и гранит',
    searchMaterials: 'Пребарај материјали по назив, код...',
    standardMaterials: 'Материјали', handcraftMaterials: 'Рачно изработени материјали',
    noMaterialsYet: 'Нема материјали', noHandcraftYet: 'Нема рачно изработени материјали',
    addMaterialBtn: 'Додади Материјал', editMaterial: 'Уреди Материјал', addMaterialTitle: 'Додади Материјал',
    materialType: 'Тип на Материјал', materialName: 'Назив на Материјал', materialCode: 'Код на Материјал',
    pricePerM2: 'Цена по м²', price: 'Цена (EUR)', count: 'Количина',
    deleteMaterial: 'Избриши Материјал', deleteMaterialConfirm: 'Дали сте сигурни дека сакате да го избришете овој материјал?',
    delete: 'Избриши', code: 'Код',
    carInsuranceTitle: 'Авто Осигурување', carInsuranceSub: 'Следете полиси за осигурување на возила',
    searchCars: 'Пребарај по назив или регистарска табличка...',
    noCarsRegistered: 'Нема регистрирани возила', noCarsFound: 'Нема пронајдено возила',
    addFirstVehicle: 'Додадете го вашето прво возило',
    tryDifferentSearch: 'Обидете се со друг термин',
    addCar: 'Додади Возило', editCarInsurance: 'Уреди Осигурување', addCarInsurance: 'Додади Осигурување',
    carName: 'Назив на Возило (Марка и Модел)', plateNumber: 'Регистарска Табличка',
    startDate: 'Почетен Датум', endDate: 'Краен Датум',
    carCol: 'Возило', plateCol: 'Табличка', statusCol: 'Статус',
    active: 'Активно', expiringSoon: 'Наскоро истекува', expired: 'Истечено',
    deleteCar: 'Избриши Возило', deleteCarConfirm: 'Дали сте сигурни дека сакате да го избришете ова возило?',
  },

  al: {
    create: 'Krijo', orders: 'Porosi', bilanc: 'Bilanc', materials: 'Materialet', carInsurance: 'Sigurimi i Makinës',
    createOrder: 'Krijo Porosi', createOrderSub: 'Plotësoni detajet për të krijuar një porosi të re',
    clientInfo: 'Informacioni i Klientit', fullName: 'Emri i Plotë', phoneNumber: 'Numri i Telefonit',
    location: 'Vendndodhja', dueDate: 'Data e Afatit', materialsLabel: 'Materialet',
    addMaterial: 'Shto Material', selectMaterial: 'Zgjidhni një material', dimensions: 'Dimensionet (metra)',
    quantity: 'Sasia', pricePerUnit: 'Çmimi për njësi', total: 'Totali',
    additionalCosts: 'Kostot Shtesë', addCost: 'Shto Kosto', noAdditionalCosts: 'Nuk ka kosto shtesë.',
    amountEur: 'Shuma (EUR)', reasonCost: 'Arsyeja e kostos', comment: 'Koment',
    commentPlaceholder: 'Shënime ose udhëzime të veçanta...', calculated: 'Llogaritur',
    cost: 'Kosto', cancel: 'Anulo', createOrderBtn: 'Krijo Porosi',
    noMaterialsAvailable: 'Nuk ka materiale. Shtoni në', first: 'fillimisht',
    item: 'Artikull',
    ordersTitle: 'Porosi', ordersSub: 'Menaxhoni dhe gjurmoni të gjitha porositë',
    searchOrders: 'Kërko porosi sipas emrit, materialit, vendndodhjes...',
    pending: 'Në pritje', approved: 'Aprovuar', declined: 'Refuzuar',
    noOrders: 'Nuk ka porosi', noPendingOrders: 'Nuk ka porosi në pritje',
    noApprovedOrders: 'Nuk ka porosi të aprovuara', noDeclinedOrders: 'Nuk ka porosi të refuzuara',
    fullNameCol: 'Emri i Plotë', materialCol: 'Material(et)', priceCol: 'Çmimi (EUR)', actionsCol: 'Veprimet',
    details: 'Detaje', orderDetails: 'Detajet e Porosisë', phone: 'Telefon',
    close: 'Mbyll', print: 'Printo', saveChanges: 'Ruaj Ndryshimet', editOrder: 'Ndrysho Porosinë',
    deleteOrderConfirm: 'Fshi këtë porosi përgjithmonë?',
    bilancTitle: 'Bilanc', bilancSub: 'Gjurmoni borxhet dhe pagesat për porositë e aprovuara',
    borxhe: 'Borxhe', tePaguara: 'Të Paguara', totaliBorxheve: 'Totali i Borxheve',
    pjeserishtTePaguara: 'Pjesërisht të Paguara', totalRemainingUnpaid: 'Totali i papaguar',
    totalPartialPayments: 'Totali i pagesave të pjesshme', totalPaguara: 'Totali i Paguar',
    noOutstandingDebts: 'Nuk ka borxhe', noPaidOrders: 'Nuk ka porosi të paguara',
    approvedOrdersAppear: 'Porositë e aprovuara me bilancë do të shfaqen këtu',
    paidOrdersAppear: 'Porositë e paguara plotësisht do të shfaqen këtu',
    searchBilanc: 'Kërko sipas emrit, materialit, vendndodhjes...',
    totalCol: 'Totali (EUR)', paidCol: 'Paguar (EUR)', remainingCol: 'Mbetur (EUR)',
    ePaguar: 'E Paguar', kthejeNeBorxhe: 'Ktheje në Borxhe',
    paymentTitle: 'Pagesë', toBePaid: 'Për t\'u Paguar', addTransaction: 'Shto Transaksion',
    subtractPayment: 'Zbrit një pagesë të klientit', addCorrection: 'Shto korrigjim', apply: 'Apliko',
    payment: 'Pagesë', correction: 'Korrigjim', remaining: 'Mbetur', paid: 'Paguar',
    materialsTitle: 'Materialet', materialsSub: 'Menaxhoni inventarin e gurit dhe granitit',
    searchMaterials: 'Kërko materiale sipas emrit, kodit...',
    standardMaterials: 'Materialet', handcraftMaterials: 'Materialet e Punuara me Dorë',
    noMaterialsYet: 'Nuk ka materiale', noHandcraftYet: 'Nuk ka materiale të punuara me dorë',
    addMaterialBtn: 'Shto Material', editMaterial: 'Ndrysho Materialin', addMaterialTitle: 'Shto Material',
    materialType: 'Lloji i Materialit', materialName: 'Emri i Materialit', materialCode: 'Kodi i Materialit',
    pricePerM2: 'Çmimi për m²', price: 'Çmimi (EUR)', count: 'Sasia',
    deleteMaterial: 'Fshi Materialin', deleteMaterialConfirm: 'Jeni të sigurt që doni ta fshini këtë material?',
    delete: 'Fshi', code: 'Kodi',
    carInsuranceTitle: 'Sigurimi i Makinës', carInsuranceSub: 'Gjurmoni politikat e sigurimit të automjeteve',
    searchCars: 'Kërko sipas emrit të makinës ose numrit të targës...',
    noCarsRegistered: 'Nuk ka makina të regjistruara', noCarsFound: 'Nuk u gjet asnjë makinë',
    addFirstVehicle: 'Shtoni automjetin tuaj të parë',
    tryDifferentSearch: 'Provoni një kërkim tjetër',
    addCar: 'Shto Makinë', editCarInsurance: 'Ndrysho Sigurimin', addCarInsurance: 'Shto Sigurimin',
    carName: 'Emri i Makinës (Marka dhe Modeli)', plateNumber: 'Numri i Targës',
    startDate: 'Data e Fillimit', endDate: 'Data e Mbarimit',
    carCol: 'Makina', plateCol: 'Targa', statusCol: 'Statusi',
    active: 'Aktiv', expiringSoon: 'Skadon së shpejti', expired: 'Skaduar',
    deleteCar: 'Fshi Makinën', deleteCarConfirm: 'Jeni të sigurt që doni ta fshini këtë rekord sigurimi?',
  }
};

export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LanguageContext);
  if (!context) {
    return { lang: 'en', setLang: () => {}, t: translations.en };
  }
  return context;
}